export const localidades = [
  { value: "Agua Amarga", label: "Agua Amarga" },
  { value: "Alvaro Obregón", label: "Alvaro Obregón" },
  { value: "Boca del Alamo", label: "Boca del Alamo" },
  { value: "Colonia 2 de Abril", label: "Colonia 2 de Abril" },
  { value: "Conquista Agraria", label: "Conquista Agraria" },
  { value: "Ejido Alfredo B. Bonfil", label: "Ejido Alfredo B. Bonfil" },
  { value: "Ejido Juan Dominguez Cota", label: "Ejido Juan Dominguez Cota" },
  { value: "El Aguaje", label: "El Aguaje" },
  { value: "El Ancón", label: "El Ancón" },
  { value: "El Cardonal", label: "El Cardonal" },
  { value: "El Carrizal", label: "El Carrizal" },
  { value: "El Cien", label: "El Cien" },
  { value: "El Pescadero", label: "El Pescadero" },
  { value: "El Refugio", label: "El Refugio" },
  { value: "El Rosario", label: "El Rosario" },
  { value: "El Saltito", label: "El Saltito" },
  { value: "El Sargento", label: "El Sargento" },
  { value: "El Triunfo", label: "El Triunfo" },
  { value: "Elias Calles", label: "Elias Calles" },
  { value: "La Matanza", label: "La Matanza" },
  { value: "La Trinidad", label: "La Trinidad" },
  { value: "La Ventana", label: "La Ventana" },
  { value: "Las Playitas", label: "Las Playitas" },
  { value: "Las Pocitas", label: "Las Pocitas" },
  { value: "Los Barriles", label: "Los Barriles" },
  { value: "Los Divisaderos", label: "Los Divisaderos" },
  { value: "Los Planes", label: "Los Planes" },
  { value: "Los Tamales", label: "Los Tamales" },
  { value: "Melitón Alvañez", label: "Melitón Alvañez" },
  { value: "Puerto Chale", label: "Puerto Chale" },
  { value: "Reforma Agraria I", label: "Reforma Agraria I" },
  { value: "Reforma Agraria II", label: "Reforma Agraria II" },
  { value: "San Antonio", label: "San Antonio" },
  { value: "San Bartolo", label: "San Bartolo" },
  { value: "San Evaristo", label: "San Evaristo" },
  { value: "San Hilario", label: "San Hilario" },
  { value: "San Jacinto", label: "San Jacinto" },
  { value: "San Pedro", label: "San Pedro" },
  { value: "Santa Rita", label: "Santa Rita" },
  { value: "Todos Santos", label: "Todos Santos" },
  { value: "La Paz", label: "La Paz" },
  { value: "Centenario", label: "Centenario" },
  { value: "Chametla", label: "Chametla" },
];
